const topics = [
  "What time period would you travel to?",
  "What is one thing you can’t live without?",
  "What is your least favorite chore?",
  "What is your earliest memory?",
  "Who are you most thankful for and why?",
  "Where do you want to go on the next family vacation?",
  "What’s the nicest thing a family member has ever done for you?",
  "What is your favorite TV show?",
  "What was the biggest punishment you’ve ever received?",
  "If you could describe yourself in three words, what would they be?",
  "What would be the first thing you would do if you traded places with your family member?",
  "What instrument would you like to play?",
  "Dogs 🐶 or cats 🐱?",
  "What is your favorite holiday?",
  "Chocolate 🍫 or Vanilla 🍦?",
  "If you could get all your family members to donate to a charity, what would it be and why?",
  "Would you want to live on a boat, a mountain or an island?",
  "What makes you most proud?",
  "What three things are you most grateful for?",
  "Who do you count on the most for help?",
  "What would make you (if parent) most upset? A tattoo, a nose ring or a bad boyfriend/girlfriend?",
  "What would be your ideal day?",
  "What makes you the happiest?",
  "If you could spend an entire day with a family member, who would it be and why?",
  "If you could be an animal, what would it be and why?",
  "If you could be any age, what age would you choose?",
  "What’s one thing you’ve won and how did you win it?",
  "What did you think was the most challenging part of being a kid?",
  "When is the last time you laughed so hard that you cried?",
  "What are the top three things on your bucket list?",
  "How do you think you will die?",
  "What has been the lowest point of your life?",
  "If you could ask for a miracle, what would it be?",
  "Where do you see yourself in five years?",
  "What is the biggest risk you’ve ever taken?",
  "What would your ideal life look like?",
  "If someone gave you an envelope with your death date inside of it, would you open it?",
  "When have you been the most happy?",
  "Do you know anyone who is living their life to the fullest?",
  "What is your idea of the perfect day?",
  "Who has been the most influential person in your life and why?",
  "What book had a big influence on you?",
  "Do you think your priorities have changed since you were younger?",
  "What is the most memorable lesson you learned from your parents?",
  "What does success mean to you?",
  "What is the most difficult thing you’ve ever done?",
  "What scares you most about your future?",
  "What keeps you up at night?",
];
module.exports = topics;
